import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-fqhc-wrap-payment-reconciliation",
  "engine": "recovery",
  "title": "FQHC Wrap Payment Reconciliation",
  "shortTitle": "FQHC Wrap Payment Reconciliation",
  "tagline": "Recover state wrap payments by reconciling managed-care revenue to the applicable PPS or alternative payment entitlement.",
  "industry": "Community Health Finance",
  "buyer": "Federally qualified health centers",
  "uiPort": 4653,
  "apiPort": 5653,
  "accent": "#0369a1",
  "currency": "USD",
  "primaryOutcome": "FQHC Wrap Payment Reconciliation converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect PPS rates, APM rates, managed-care encounters, paid claims, qualifying visits, same-day services, supplemental payments, remittances, and state submissions in one accountable workflow. Recover state wrap payments by reconciling managed-care revenue to the applicable PPS or alternative payment entitlement.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "FQHC Wrap Payment Reconciliation evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("site-rate-registry","FWP01","Site rate registry","Execute site rate registry using PPS rates, APM rates, managed-care encounters, paid claims, qualifying visits, same-day services, supplemental payments, remittances, and state submissions.","Produce a governed site rate registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Health Center / Managed-Care Encounter","text","Health Center / Managed-Care Encounter · Standard Case"],["caseReference","Site rate registry Reference","text","FWP01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",645000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",780450],["domainDriver","Payment Method","select","PPS wrap",["PPS wrap","APM wrap","Supplemental pool"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Site rate registry case","Managed-care contract mapping case","Encounter ingestion case","Qualifying visit validation case","Same-day visit rules case"]}),
feature("managed-care-contract-mapping","FWP02","Managed-care contract mapping","Execute managed-care contract mapping using PPS rates, APM rates, managed-care encounters, paid claims, qualifying visits, same-day services, supplemental payments, remittances, and state submissions.","Produce a governed managed-care contract mapping decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Health Center / Managed-Care Encounter","text","Health Center / Managed-Care Encounter · Standard Case"],["caseReference","Managed-care contract mapping Reference","text","FWP02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",645000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",780450],["domainDriver","Payment Method","select","PPS wrap",["PPS wrap","APM wrap","Supplemental pool"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Site rate registry case","Managed-care contract mapping case","Encounter ingestion case","Qualifying visit validation case","Same-day visit rules case"]}),
feature("encounter-ingestion","FWP03","Encounter ingestion","Execute encounter ingestion using PPS rates, APM rates, managed-care encounters, paid claims, qualifying visits, same-day services, supplemental payments, remittances, and state submissions.","Produce a governed encounter ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Health Center / Managed-Care Encounter","text","Health Center / Managed-Care Encounter · Standard Case"],["caseReference","Encounter ingestion Reference","text","FWP03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",645000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",780450],["domainDriver","Payment Method","select","PPS wrap",["PPS wrap","APM wrap","Supplemental pool"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Site rate registry case","Managed-care contract mapping case","Encounter ingestion case","Qualifying visit validation case","Same-day visit rules case"]}),
feature("qualifying-visit-validation","FWP04","Qualifying visit validation","Execute qualifying visit validation using PPS rates, APM rates, managed-care encounters, paid claims, qualifying visits, same-day services, supplemental payments, remittances, and state submissions.","Produce a governed qualifying visit validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Health Center / Managed-Care Encounter","text","Health Center / Managed-Care Encounter · Standard Case"],["caseReference","Qualifying visit validation Reference","text","FWP04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",645000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",780450],["domainDriver","Payment Method","select","PPS wrap",["PPS wrap","APM wrap","Supplemental pool"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Site rate registry case","Managed-care contract mapping case","Encounter ingestion case","Qualifying visit validation case","Same-day visit rules case"]}),
feature("same-day-visit-rules","FWP05","Same-day visit rules","Execute same-day visit rules using PPS rates, APM rates, managed-care encounters, paid claims, qualifying visits, same-day services, supplemental payments, remittances, and state submissions.","Produce a governed same-day visit rules decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Health Center / Managed-Care Encounter","text","Health Center / Managed-Care Encounter · Standard Case"],["caseReference","Same-day visit rules Reference","text","FWP05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",645000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",780450],["domainDriver","Payment Method","select","PPS wrap",["PPS wrap","APM wrap","Supplemental pool"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Site rate registry case","Managed-care contract mapping case","Encounter ingestion case","Qualifying visit validation case","Same-day visit rules case"]}),
feature("pps-rate-calculation","FWP06","PPS rate calculation","Execute pps rate calculation using PPS rates, APM rates, managed-care encounters, paid claims, qualifying visits, same-day services, supplemental payments, remittances, and state submissions.","Produce a governed pps rate calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Health Center / Managed-Care Encounter","text","Health Center / Managed-Care Encounter · Standard Case"],["caseReference","PPS rate calculation Reference","text","FWP06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",645000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",780450],["domainDriver","Payment Method","select","PPS wrap",["PPS wrap","APM wrap","Supplemental pool"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Site rate registry case","Managed-care contract mapping case","Encounter ingestion case","Qualifying visit validation case","Same-day visit rules case"]}),
feature("apm-rate-calculation","FWP07","APM rate calculation","Execute apm rate calculation using PPS rates, APM rates, managed-care encounters, paid claims, qualifying visits, same-day services, supplemental payments, remittances, and state submissions.","Produce a governed apm rate calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Health Center / Managed-Care Encounter","text","Health Center / Managed-Care Encounter · Standard Case"],["caseReference","APM rate calculation Reference","text","FWP07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",645000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",780450],["domainDriver","Payment Method","select","PPS wrap",["PPS wrap","APM wrap","Supplemental pool"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Site rate registry case","Managed-care contract mapping case","Encounter ingestion case","Qualifying visit validation case","Same-day visit rules case"]}),
feature("mco-payment-allocation","FWP08","MCO payment allocation","Execute mco payment allocation using PPS rates, APM rates, managed-care encounters, paid claims, qualifying visits, same-day services, supplemental payments, remittances, and state submissions.","Produce a governed mco payment allocation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Health Center / Managed-Care Encounter","text","Health Center / Managed-Care Encounter · Standard Case"],["caseReference","MCO payment allocation Reference","text","FWP08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",645000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",780450],["domainDriver","Payment Method","select","PPS wrap",["PPS wrap","APM wrap","Supplemental pool"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Site rate registry case","Managed-care contract mapping case","Encounter ingestion case","Qualifying visit validation case","Same-day visit rules case"]}),
feature("wrap-amount-calculation","FWP09","Wrap amount calculation","Execute wrap amount calculation using PPS rates, APM rates, managed-care encounters, paid claims, qualifying visits, same-day services, supplemental payments, remittances, and state submissions.","Produce a governed wrap amount calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Health Center / Managed-Care Encounter","text","Health Center / Managed-Care Encounter · Standard Case"],["caseReference","Wrap amount calculation Reference","text","FWP09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",645000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",780450],["domainDriver","Payment Method","select","PPS wrap",["PPS wrap","APM wrap","Supplemental pool"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Site rate registry case","Managed-care contract mapping case","Encounter ingestion case","Qualifying visit validation case","Same-day visit rules case"]}),
feature("duplicate-encounter-control","FWP10","Duplicate encounter control","Execute duplicate encounter control using PPS rates, APM rates, managed-care encounters, paid claims, qualifying visits, same-day services, supplemental payments, remittances, and state submissions.","Produce a governed duplicate encounter control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Health Center / Managed-Care Encounter","text","Health Center / Managed-Care Encounter · Standard Case"],["caseReference","Duplicate encounter control Reference","text","FWP10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",645000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",780450],["domainDriver","Payment Method","select","PPS wrap",["PPS wrap","APM wrap","Supplemental pool"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Site rate registry case","Managed-care contract mapping case","Encounter ingestion case","Qualifying visit validation case","Same-day visit rules case"]}),
feature("state-submission-file","FWP11","State submission file","Execute state submission file using PPS rates, APM rates, managed-care encounters, paid claims, qualifying visits, same-day services, supplemental payments, remittances, and state submissions.","Produce a governed state submission file decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Health Center / Managed-Care Encounter","text","Health Center / Managed-Care Encounter · Standard Case"],["caseReference","State submission file Reference","text","FWP11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",645000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",780450],["domainDriver","Payment Method","select","PPS wrap",["PPS wrap","APM wrap","Supplemental pool"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Site rate registry case","Managed-care contract mapping case","Encounter ingestion case","Qualifying visit validation case","Same-day visit rules case"]}),
feature("error-response-remediation","FWP12","Error response remediation","Execute error response remediation using PPS rates, APM rates, managed-care encounters, paid claims, qualifying visits, same-day services, supplemental payments, remittances, and state submissions.","Produce a governed error response remediation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Health Center / Managed-Care Encounter","text","Health Center / Managed-Care Encounter · Standard Case"],["caseReference","Error response remediation Reference","text","FWP12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",645000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",780450],["domainDriver","Payment Method","select","PPS wrap",["PPS wrap","APM wrap","Supplemental pool"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Site rate registry case","Managed-care contract mapping case","Encounter ingestion case","Qualifying visit validation case","Same-day visit rules case"]}),
feature("payment-receipt-matching","FWP13","Payment receipt matching","Execute payment receipt matching using PPS rates, APM rates, managed-care encounters, paid claims, qualifying visits, same-day services, supplemental payments, remittances, and state submissions.","Produce a governed payment receipt matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Health Center / Managed-Care Encounter","text","Health Center / Managed-Care Encounter · Standard Case"],["caseReference","Payment receipt matching Reference","text","FWP13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",645000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",780450],["domainDriver","Payment Method","select","PPS wrap",["PPS wrap","APM wrap","Supplemental pool"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Site rate registry case","Managed-care contract mapping case","Encounter ingestion case","Qualifying visit validation case","Same-day visit rules case"]}),
feature("aging-and-appeal-workflow","FWP14","Aging and appeal workflow","Execute aging and appeal workflow using PPS rates, APM rates, managed-care encounters, paid claims, qualifying visits, same-day services, supplemental payments, remittances, and state submissions.","Produce a governed aging and appeal workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Health Center / Managed-Care Encounter","text","Health Center / Managed-Care Encounter · Standard Case"],["caseReference","Aging and appeal workflow Reference","text","FWP14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",645000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",780450],["domainDriver","Payment Method","select","PPS wrap",["PPS wrap","APM wrap","Supplemental pool"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Site rate registry case","Managed-care contract mapping case","Encounter ingestion case","Qualifying visit validation case","Same-day visit rules case"]}),
feature("site-plan-analytics","FWP15","Site plan analytics","Execute site plan analytics using PPS rates, APM rates, managed-care encounters, paid claims, qualifying visits, same-day services, supplemental payments, remittances, and state submissions.","Produce a governed site plan analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Health Center / Managed-Care Encounter","text","Health Center / Managed-Care Encounter · Standard Case"],["caseReference","Site plan analytics Reference","text","FWP15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",645000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",780450],["domainDriver","Payment Method","select","PPS wrap",["PPS wrap","APM wrap","Supplemental pool"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Site rate registry case","Managed-care contract mapping case","Encounter ingestion case","Qualifying visit validation case","Same-day visit rules case"]})
]);
